"""Initial migration

Revision ID: 391fd64069b8
Revises: 
Create Date: 2024-09-16 13:39:59.337467

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '391fd64069b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cancelled_list', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('stock_code',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('required_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('required_quantity',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('grand_total', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('monthly_forecasts', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('monthly_totals', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('picklist', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('stock_code',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('required_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('required_quantity',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('stock_price', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)

    with op.batch_alter_table('weekly_forecasts', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('weekly_totals', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_totals', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('weekly_forecasts', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('stock_price', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('picklist', schema=None) as batch_op:
        batch_op.alter_column('required_quantity',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('required_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('stock_code',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('account_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('monthly_totals', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('monthly_forecasts', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('grand_total', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('cancelled_list', schema=None) as batch_op:
        batch_op.alter_column('required_quantity',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('required_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('stock_code',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('account_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###
