"""Change last_delivery_note  to VARCHAR(20)

Revision ID: 42d91fc549a8
Revises: e62925b4ca4a
Create Date: 2024-07-15 10:33:21.474164

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '42d91fc549a8'
down_revision = 'e62925b4ca4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grand_total', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('monthly_forecasts', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('monthly_totals', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('sales_order', schema=None) as batch_op:
        batch_op.alter_column('last_delivery_note',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)

    with op.batch_alter_table('weekly_forecasts', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('weekly_totals', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_totals', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('weekly_forecasts', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('sales_order', schema=None) as batch_op:
        batch_op.alter_column('last_delivery_note',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('monthly_totals', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('monthly_forecasts', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('grand_total', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###
