"""Change order_reference to BigInteger

Revision ID: f6a0ea7f80d9
Revises: 
Create Date: 2024-07-15 10:19:38.416745

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f6a0ea7f80d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grand_total', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('monthly_forecasts', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('monthly_totals', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('sales_order', schema=None) as batch_op:
        batch_op.alter_column('order_reference',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('last_delivery_note',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)

    with op.batch_alter_table('weekly_forecasts', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('weekly_totals', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_totals', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('weekly_forecasts', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('sales_order', schema=None) as batch_op:
        batch_op.alter_column('last_delivery_note',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('order_reference',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=True)

    with op.batch_alter_table('monthly_totals', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('monthly_forecasts', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('grand_total', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###
